version: "3.9"
services:
  db:
    image: postgres:15.0
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # bot:
  #   image: python:3.11.0-alpine3.14
  #   env_file:
  #     - .env
  #   dockerfile: src/Dockerfile

volumes:
  pgdata:
