version: "3.9"
services:
  db:
    image: postgres:15.0
    env_file:
      - ../.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  bot:
    build:
      context: ../src
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../.env
    depends_on:
      - db

volumes:
  pgdata:
